on:
  push:
    branches: 
    - main
    paths:
    - 'src/**'

  workflow_dispatch:

jobs:
  SFPT-Deploy-Action:
    name: SFTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Use Node,js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    
    - name: Build Project
      run: |
        npm install
        CI=false npm run build
        cp .htaccess build/.htaccess
      env: 
        REACT_APP_EMAILJS_SERVICE_ID: ${{ secrets.REACT_APP_EMAILJS_SERVICE_ID }}
        REACT_APP_EMAILJS_TEMPLATE_ID: ${{ secrets.REACT_APP_EMAILJS_TEMPLATE_ID }}
        REACT_APP_EMAILJS_USER_ID: ${{ secrets.REACT_APP_EMAILJS_USER_ID }}
    
    - name: SFTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: build
        METHOD: sftp
        PORT: 22
        ARGS: --delete
        LOG_LEVEL: minimal
        SECURITY: strict
